name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: '8.6'
            variant: 'CS'
          - version: '8.7'
            variant: 'CS'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Racket
      uses: Bogdanp/setup-racket@v1.8.1
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.variant }}
        version: ${{ matrix.version }}
        packages: 'crypto'
    - name: Build package
      run: raco pkg install --auto otp/ otp-lib/ typed-otp-lib/ otp-doc/
    - name: Run tests
      run: raco test otp otp-lib typed-otp-lib
